### ISSUE TITLE
Add mocks to accommodate flood_risk_engine_usage

### ISSUE THREAD

**Issue by woodpigeon** [DEFRA/ea-address_lookup#18]
Review wherever fre is using VCR for address mocking, and ensure we have built in mocks to simulate all those conditions, so VCR can be removed from fre.
For example see the discussion on [this PR](https://github.com/EnvironmentAgency/flood-risk-engine/pull/149).

**Comment by autotelik** [comment]
Given that VCR is an excellent mocking mechanism, and seems to be fine in travis now, not sure why we are wasting time replacing a superior system with an inferior one ?

**Comment by Cruikshanks** [comment]
Closing as this repo has been superseded by [Defra ruby address](https://github.com/DEFRA/defra-ruby-address)
